[package]
name = "cargo-build_script_build-parser"
version = "0.1.10"
edition = "2024"

[dev-dependencies]
tempfile = "3.20.0"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
regex = "1.11.1"
