[package]
name = "build-rs-libnix"
edition.workspace = true
version.workspace = true

[dependencies]
regex = { workspace = true }
colored = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tempfile = "3.16.0"
